### ISSUE TITLE
Redis configuration is not caching any request

### ISSUE THREAD

**Issue by carlosjgp** [Comcast/trickster#253]
After configuring Trcikster to use AWS ElastiCache/Redis 5.0.4, deployed as Master + 2 Replicas and without cluster mode enabled.

Using Trickster 1.0-beta8 image

Deployed on K8s with 3 replicas and exposing Trickester through an Ingress to allow Grafana to use it as Datasource.

Every time Grafana runs a query Trickster misses the cache, even copying the request from Grafana and running it with curl multiple times it keeps failing the cache

```
    [caches]

        [caches.default]
        # cache_type defines what kind of cache Trickster uses
        # options are 'bbolt', 'filesystem', 'memory', 'redis' and 'redis_cluster'
        # The default is 'memory'.
        type = 'redis'

        # compression determines whether the cache should be compressed. default is true
        # changing the compression setting will leave orphans in your cache for the duration of timeseries_ttl_secs
        compression = true

        # timeseries_ttl_secs defines the relative expiration of cached timeseries. default is 6 hours (21600 seconds)
        timeseries_ttl_secs = 21600

        # fastforward_ttl_secs defines the relative expiration of cached fast forward data. default is 15s
        fastforward_ttl_secs = 15

        # object_ttl_secs defines the relative expiration of generically cached (non-timeseries) objects. default is 30s
        object_ttl_secs = 30

            ### Configuration options for the Cache Index
            # The Cache Index handles key management and retention for bbolt, filesystem and memory
            # Redis handles those functions natively and does not use the Trickster's Cache Index
            [caches.default.index]

            # reap_interval_secs defines how long the Cache Index reaper sleeps between reap cycles. Default is 3 (3s)
            reap_interval_secs = 3

            # flush_interval_secs sets how often the Cache Index saves its metadata to the cache from application memory. Default is 5 (5s)
            flush_interval_secs = 5

            # max_size_bytes indicates how large the cache can grow in bytes before the Index evicts least-recently-accessed items. default is 512MB
            max_size_bytes = 536870912

            # max_size_backoff_bytes indicates how far below max_size_bytes the cache size must be to complete a byte-size-based eviction exercise. default is 16MB
            max_size_backoff_bytes = 16777216

            # max_size_objects indicates how large the cache can grow in objects before the Index evicts least-recently-accessed items. default is 0 (infinite)
            max_size_objects = 0

            # max_size_backoff_objects indicates how far under max_size_objects the cache size must be to complete object-size-based eviction exercise. default is 100
            max_size_backoff_objects = 100



            ### Configuration options when using a Redis Cache
            [caches.default.redis]
            # protocol defines the protocol for connecting to redis ('unix' or 'tcp') 'tcp' is default
            protocol = 'tcp'
            # endpoint defines the fqdn+port or path to a unix socket file for connecting to redis
            # default is 'redis:6379'
            endpoint = 'redis-common.external-service.svc.cluster.local:6379'
            # password provides the redis password
            # default is empty
            password = ''
```

**Comment by jranson** [comment]
hey @cpower, would you be interested in giving me an assist with debugging trickster backed by redis elasticache?

**Comment by carlosjgp** [comment]
Re tested it with `1.0-beta9` since `8` is now not available on DockerHub

Still not working

**Comment by carlosjgp** [comment]
These are the logs generated when I curl trickster API
```
time=2019-07-22T09:38:10.14473123Z app=trickster caller=cache/redis/redis.go:82 level=debug event="redis cache store" key=thanos-query.monitoring.svc.cluster.local:9090.a6ea582c6507913776522ef392a43658.sz
time=2019-07-22T09:38:18.389146941Z app=trickster caller=cache/redis/redis.go:90 level=debug event="redis cache miss" key=thanos-query.monitoring.svc.cluster.local:9090.35f1a14ee44fa7d814dbde65f1963728.sz
time=2019-07-22T09:38:18.780289939Z app=trickster caller=proxy/engines/access_logs.go:23 level=debug event="upstream request" uri="http://thanos-query.monitoring.svc.cluster.local:9090/api/v1/query_range?end=1563782400&query=sum+by+%28servicename%29+%28label_replace%28rate%28rt%3Aclient%3Afailures%7Brt%3D%22outgoing%22%7D%5B1m%5D%29%2C+%22servicename%22%2C+%22%241%22%2C+%22client%22%2C+%22.%2A%2F%28.%2A%29%24%22%29%29&start=1563771600&step=40" durationMS=390 method=GET originType=prometheus handlerName=QueryRangeHandler userAgent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36" code=200 size=70312 originName=default
time=2019-07-22T09:38:18.796308844Z app=trickster caller=proxy/engines/deltaproxycache.go:323 level=debug event="delta routine completed" cacheKey=thanos-query.monitoring.svc.cluster.local:9090.35f1a14ee44fa7d814dbde65f1963728 cacheStatus=kmiss reqStart=1563771600 reqEnd=1563782400
time=2019-07-22T09:38:18.891455876Z app=trickster caller=proxy/engines/cache.go:62 level=debug event="compressing cached data" cacheKey=thanos-query.monitoring.svc.cluster.local:9090.35f1a14ee44fa7d814dbde65f1963728.sz
time=2019-07-22T09:38:18.891564599Z app=trickster caller=cache/redis/redis.go:82 level=debug event="redis cache store" key=thanos-query.monitoring.svc.cluster.local:9090.35f1a14ee44fa7d814dbde65f1963728.sz
time=2019-07-22T09:38:27.927527667Z app=trickster caller=cache/redis/redis.go:90 level=debug event="redis cache miss" key=thanos-query.monitoring.svc.cluster.local:9090.35f1a14ee44fa7d814dbde65f1963728.sz
time=2019-07-22T09:38:28.482895556Z app=trickster caller=proxy/engines/access_logs.go:23 level=debug event="upstream request" originType=prometheus handlerName=QueryRangeHandler userAgent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36" size=70312 durationMS=555 originName=default uri="http://thanos-query.monitoring.svc.cluster.local:9090/api/v1/query_range?end=1563782400&query=sum+by+%28servicename%29+%28label_replace%28rate%28rt%3Aclient%3Afailures%7Brt%3D%22outgoing%22%7D%5B1m%5D%29%2C+%22servicename%22%2C+%22%241%22%2C+%22client%22%2C+%22.%2A%2F%28.%2A%29%24%22%29%29&start=1563771600&step=40" code=200 method=GET
time=2019-07-22T09:38:28.496862665Z app=trickster caller=proxy/engines/deltaproxycache.go:323 level=debug event="delta routine completed" reqStart=1563771600 reqEnd=1563782400 cacheKey=thanos-query.monitoring.svc.cluster.local:9090.35f1a14ee44fa7d814dbde65f1963728 cacheStatus=kmiss
time=2019-07-22T09:38:28.583136173Z app=trickster caller=proxy/engines/cache.go:62 level=debug event="compressing cached data" cacheKey=thanos-query.monitoring.svc.cluster.local:9090.35f1a14ee44fa7d814dbde65f1963728.sz
time=2019-07-22T09:38:28.583278391Z app=trickster caller=cache/redis/redis.go:82 level=debug event="redis cache store" key=thanos-query.monitoring.svc.cluster.local:9090.35f1a14ee44fa7d814dbde65f1963728.sz
```

It works when I switch to `memory`

**Comment by cpower** [comment]
I was able to get trickster:1.0-beta9 running in a container on an EC2 instance to work with Prometheus as the origin and AWS Elasticache Redis as the cache

Trickster - v1.0-beta9
Prometheus - 2.11.1

Both running via a Docker compose file on an EC2 instance in AWS

AWS Elasticache Redis - v5.0.4
Master + 2 Replicas

**Comment by cpower** [comment]
@carlosjgp - were you deploying Redis via Elasticache in AWS or did you deploy Redis into a K8S cluster?

**Comment by cpower** [comment]
Here's the Trickster Redis configuration tested against the AWS Elasticache Redis instance:

```
[caches]

    [caches.default]
    type = 'redis'
    compression = true
    timeseries_ttl_secs = 21600
    fastforward_ttl_secs = 15  
    object_ttl_secs = 30

        [caches.default.index]
        reap_interval_secs = 3 
        flush_interval_secs = 5 
        max_size_bytes = 536870912
        max_size_backoff_bytes = 16777216
        max_size_objects = 0
        max_size_backoff_objects = 100

        [caches.default.redis]
        client_type = 'standard'
        protocol = 'tcp'
        endpoint = 'elasticache.redacted.cache.amazonaws.com:6379'
        sentinel_master = ''
        password = ''
```

**Comment by carlosjgp** [comment]
Thanks for the quick response @cpower, I've noticed that your configuration has 2 "undocumented" properties under `[caches.default.redis]`.
- `client_type`
- `sentinel_master`
They are not present in the configuration example provided on the `v1.09-beta9` branch/tag
https://github.com/Comcast/trickster/blob/v1.09-beta9/deploy/kube/configmap.yaml#L71-L79

Answering to your question, I'm deploying it on Kubernetes caching requests between Grafana and Thanos Query

**Comment by chris-vest** [comment]
@jranson @cpower Any updates on this ticket? Do you need any more information?

**Comment by jranson** [comment]
@chris-vest Hi Chris, I am still not able to reproduce this, however, we have put a lot of work into cleaning up the kube configmap and helm charts to include all possible values for the next beta release and addressed a lot of other small issues. It should be out in the next couple of days as we get the last few things fixed up. If you wouldn't mind testing then, that might make a difference for you. Thanks again for reporting this, and sorry we don't have it fixed up for you yet.

**Comment by chris-vest** [comment]
@jranson No problem! We'll test out the latest version when it's released and go from there.

**Comment by kogent** [comment]
I experienced this as well in beta9.  After adapting to the new configuration this is working for me in beta10.

**Comment by carlosjgp** [comment]
I'm afraid we are moving away from trickster in favour of cortex ui which has now been decoupled and is compatible with any PromQL client.

You can close this ticket if you want

**Comment by jranson** [comment]
Carlos, we're sorry to see you go! Thanks for trying out Trickster, and please check in on the project periodically to see if there's anything new that can fit in your stack. The current RC1 has a lot of new features that we hope to encourage new users and contributors who can make the project even better. And we'd love for you to submit any new feature requests that might help us be more relevant to the entire cloud native landscape - including you!

**Comment by jranson** [comment]
@kogent could you confirm that this is resolved for you in RC1? Thanks very much for trying this out. We've been trying to reproduce this in order to troubleshoot further, but have been unable.

**Comment by kogent** [comment]
I was mistaken about it working in beta10.  The key for cache type changed and it was silently using memory instead of redis.  So this is still broken in beta10.  I'll try out rc1 and get back to you.

**Comment by jranson** [comment]
@kogent Thanks for checking, hopefully we can get to the bottom of this. If it is still an issue, we would like to get on a call and work through this together if you are available and interested. My contact information is on my github profile. Thank you!

**Comment by jranson** [comment]
@kogent I think we have this one figured out and baked the fix into `1.0.0-rc2`, so hopefully you've not tried rc1 yet and wouldn't mind confirming on rc2 for us. I have confirmed locally and running in ec2 with elasticache that everything looks good. Thanks for your help!

**Comment by kogent** [comment]
i deployed 1.0.1 and this is working for me..

**Comment by chfxr** [comment]
Have an similar issue, where the Redis Keys are not stored at all for one specific API.
It says always:
redis cache miss followed by redis cache remove
